apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acie-ingress
  namespace: acie
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          # Frontend (Root)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acie-frontend-service
                port:
                  number: 80

          # Java Gateway API
          - path: /api/java
            pathType: Prefix
            backend:
              service:
                name: acie-java-service
                port:
                  number: 8080

          # Python Inference API
          - path: /api/v2
            pathType: Prefix
            backend:
              service:
                name: acie-service
                port:
                  number: 80

          # API Docs
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: acie-service
                port:
                  number: 80
